---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
tvl_salaries_monthly <- tv::get_salaries(years = 2008:2021)
DT::datatable(tvl_salaries_monthly)
```

## Download yearly extra payments (bonus)

```{r bonus}
# Load the pipe operator
`%>%` <- magrittr::`%>%`

# Get yearly salary and bonus for each row in tvl_salaries_monthly (test 3 only)
salary_bonus <- tv::get_yearly_salary_and_bonus(
  data = tvl_salaries_monthly[1:3, ]
)

# Save salary_bonus in rds file
#kwb.utils::createDirectory("./inst/extdata")
#saveRDS(salary_bonus, "./inst/extdata/yearly-salary-and-bonus.rds")
#salary_bonus <- readRDS("./inst/extdata/yearly-salary-and-bonus.rds")
  
salary_bonus$percentage <- round(
  salary_bonus$extra_yearly / salary_bonus$salary_yearly * 100, 
  digits = 2L
)

DT::datatable(salary_bonus)
```

```{r bonus_summary}
bonus_summary <- salary_bonus %>%
  dplyr::group_by(union_rate, area, pay_group) %>%
  dplyr::summarise(
    min_percentage = min(percentage, na.rm = TRUE),
    max_percentage = max(percentage, na.rm = TRUE), 
    .groups = "drop"
  )

DT::datatable(bonus_summary)
```
